# Generated by Django 3.1.2 on 2020-10-16 04:05

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ourdiary', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ourdiary',
            name='like_user_set',
        ),
        migrations.AddField(
            model_name='ourdiary',
            name='likes_user',
            field=models.ManyToManyField(blank=True, related_name='like_user', through='ourdiary.Like', to=settings.AUTH_USER_MODEL),
        ),
    ]
