# Generated by Django 3.0.6 on 2020-10-16 17:09

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ourdiary', '0002_auto_20201013_1633'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ourdiary',
            name='likes_user',
        ),
        migrations.AddField(
            model_name='ourdiary',
            name='like_user_set',
            field=models.ManyToManyField(blank=True, related_name='like_user_set', through='ourdiary.Like', to=settings.AUTH_USER_MODEL),
        ),
    ]
