# Generated by Django 3.0.6 on 2020-11-18 13:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ourdiary', '0006_auto_20201117_1855'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='ourdiary.Ourdiary'),
        ),
    ]
