# Generated by Django 3.0.6 on 2020-11-19 01:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ourdiary', '0007_auto_20201118_2259'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='author',
            field=models.ForeignKey(blank=True, editable=False, on_delete=django.db.models.deletion.CASCADE, to='ourdiary.Ourdiary'),
        ),
    ]
