# Generated by Django 3.0.6 on 2020-11-19 16:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ourdiary', '0008_auto_20201119_1007'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='author',
        ),
    ]
