# Generated by Django 3.0.6 on 2020-11-19 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ourdiary', '0009_remove_comment_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='author',
            field=models.CharField(default=' ', max_length=200),
            preserve_default=False,
        ),
    ]
