# Generated by Django 3.0.6 on 2020-11-24 02:55

from django.db import migrations
import imagekit.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_profile_nickname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=imagekit.models.fields.ProcessedImageField(blank=True, default='settings.MEDIA_ROOT/profile/images/pngegg', upload_to='profile/images'),
        ),
    ]
